name = "forwarder"
type = "javascript"
workers_dev = true
compatibility_date = "2022-02-05"

[vars]
WORKERS_RS_VERSION = "0.0.8"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/forwarder"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
