name: Deploy Rust Cloudflare

on:
  # Currently too slow to be practical
  # push:
  #   branches:
  #     - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: forwarder
    steps:
      - uses: actions/checkout@v2
      # - uses: dtolnay/rust-toolchain@stable
      # Can't use `cloudflare/wrangler-action`.
      # See <https://github.com/cloudflare/wrangler-action/pull/61>
      - name: Publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: forwarder
        run: cargo install wrangler && wrangler publish
