name: Deploy Rust Cloudflare

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: which cargo
      - run: cargo --version
      - name: Publish Test
        if: github.ref != 'refs/heads/master'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish --dry-run
      - name: Publish
        if: github.ref == 'refs/heads/master'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}