name: Deploy Rust Cloudflare

on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./forwarder
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
