name: Deploy Rust Cloudflare

on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: forwarder
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: forwarder
